# Generated by Django 2.2.1 on 2019-07-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_onlinetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
