# Generated by Django 2.2.1 on 2019-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190706_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='onlinetoken',
            name='token',
            field=models.CharField(max_length=80),
        ),
    ]
