# Generated by Django 2.2.4 on 2019-08-05 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('a1bd56a3-8e09-4b65-9f85-5515dedf2a2d'), verbose_name='JWT Secret'),
        ),
    ]
