# Generated by Django 2.2.4 on 2019-08-05 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190805_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('2cf3da53-3485-4c8b-bcfe-bfa210ace9d1'), verbose_name='JWT Secret'),
        ),
    ]
