# Generated by Django 2.2.4 on 2019-08-05 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190805_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('4bd332ee-5867-41f8-bb87-6a1c978af4c9'), verbose_name='JWT Secret'),
        ),
    ]
