# Generated by Django 2.2.4 on 2019-08-05 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190805_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('05b08b12-a726-4550-aeb5-6de70845c4e4'), verbose_name='JWT Secret'),
        ),
    ]
