# Generated by Django 2.2.4 on 2019-08-05 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190805_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('8baf1431-b569-4a23-8a56-7a5e48de5687'), verbose_name='JWT Secret'),
        ),
    ]
