# Generated by Django 2.2.4 on 2019-08-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190805_0620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
