# Generated by Django 2.2.4 on 2019-08-05 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190805_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('7c30f47b-4c11-4ebf-94b1-55f8d38dcbdc'), verbose_name='JWT Secret'),
        ),
    ]
