# Generated by Django 2.2.4 on 2019-08-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190805_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('acb61377-ed43-4684-ab2f-4b10785dee30'), verbose_name='JWT Secret'),
        ),
    ]
