# Generated by Django 2.2.4 on 2019-08-05 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('cf26c33c-6d92-4cb2-8b44-b98811b2e3c4'), verbose_name='JWT Secret'),
        ),
    ]
