# Generated by Django 2.2.4 on 2019-08-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190805_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('a689d652-33af-422d-a1a6-4317f71cda89'), verbose_name='JWT Secret'),
        ),
    ]
