# Generated by Django 2.2.4 on 2019-08-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190805_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('fe1a725f-4bc5-409b-9547-6950211e634c'), verbose_name='JWT Secret'),
        ),
    ]
