# Generated by Django 2.2.4 on 2019-08-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190805_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('618d48c6-17c9-4301-841b-36fcbd585fc0'), verbose_name='JWT Secret'),
        ),
    ]
