# Generated by Django 2.2.4 on 2019-08-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190805_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('9bfc2c96-ac6a-4764-8a72-da77d2803b27'), verbose_name='JWT Secret'),
        ),
    ]
