# Generated by Django 2.2.4 on 2019-08-05 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190805_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('36e23f58-a603-40ef-b4d8-377c09fd76ef'), verbose_name='JWT Secret'),
        ),
    ]
