# Generated by Django 2.2.4 on 2019-08-05 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190805_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('e8b53094-c6a2-4e37-a4d8-8175ec3bf8a1'), verbose_name='JWT Secret'),
        ),
    ]
